load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["port.go"],
    importpath = "github.com/rickypai/golang-boilerplate/common",
    visibility = ["//visibility:public"],
)
